---
- name: Radarr Container
  become: true
  docker_container:
    name: radarr
    restart_policy: unless-stopped
    image: linuxserver/radarr
    volumes:
      - /home/{{ user }}/radarr/config:/config
      - /mnt/Media/Downloads:/downloads
      - /mnt/Media/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "7878:7878"

- name:  Sonarr Container
  become: true
  docker_container:
    name: sonarr
    restart_policy: unless-stopped
    image: linuxserver/sonarr
    volumes:
      - /home/{{ user }}/sonarr/config:/config
      - /mnt/Media/TV:/tv
      - /mnt/Media/Downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "8989:8989"

- name: NZBGet Container
  become: true
  docker_container:
    name: nzbget
    restart_policy: unless-stopped
    image: linuxserver/nzbget
    volumes:
      - /home/{{ user }}/nzbget/config:/config
      - /mnt/Media/Downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "6789:6789"

- name: Deluge Container
  become: true
  docker_container:
    name: deluge
    restart_policy: unless-stopped
    image: linuxserver/deluge
    network_mode: host
    volumes:
      - /home/{{ user }}/deluge/config:/config
      - /mnt/Media/Downloads:/downloads
    env:
      PGID: 1000
      PUID: 1000
      UMASK_SET: 022
      TZ: America/Edmonton

- name: Jackett Container
  become: true
  docker_container:
    name: jackett
    restart_policy: unless-stopped
    image: linuxserver/jackett
    volumes:
      - /home/{{ user }}/jackett/config:/config
      - /mnt/Media/Downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
    ports:
      - "9117:9117"

- name: Plex Container
  become: true
  docker_container:
    name: plex
    network_mode: host
    restart_policy: unless-stopped
    image: linuxserver/plex
    volumes:
      - /home/{{ user }}/plex/config:/config
      - /mnt/Media/TV:/data/tvshows 
      - /mnt/Media/Movies:/data/movies 
    env:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
      VERSION: latest