---
- name: Radarr Container
  become: true
  docker_container:
    name: radarr
    restart_policy: unless-stopped
    image: linuxserver/radarr
    volumes:
      - "{{ config_dir }}/radarr/config:/config"
      - "{{ downloads_dir }}:/downloads"
      - "{{ movies_dir }}:/movies"
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "7878:7878"

- name:  Sonarr Container
  become: true
  docker_container:
    name: sonarr
    restart_policy: unless-stopped
    image: linuxserver/sonarr
    volumes:
      - "{{ config_dir }}/sonarr/config:/config"
      - "{{ tv_dir }}:/tv"
      - "{{ downloads_dir }}:/downloads"
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "8989:8989"

- name: NZBGet Container
  become: true
  docker_container:
    name: nzbget
    restart_policy: unless-stopped
    image: linuxserver/nzbget
    volumes:
      - "{{ config_dir }}/nzbget/config:/config"
      - "{{ downloads_dir }}:/downloads"
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
    ports:
      - "6789:6789"

- name: Deluge Container
  become: true
  docker_container:
    name: deluge
    restart_policy: unless-stopped
    image: linuxserver/deluge
    network_mode: host
    volumes:
      - "{{ config_dir }}/deluge/config:/config"
      - "{{ downloads_dir }}:/downloads"
    env:
      PGID: 1000
      PUID: 1000
      UMASK_SET: 022
      TZ: "{{ timezone }}"

- name: Jackett Container
  become: true
  docker_container:
    name: jackett
    restart_policy: unless-stopped
    image: linuxserver/jackett
    volumes:
      - "{{ config_dir }}/jackett/config:/config"
      - "{{ downloads_dir }}:/downloads"
      - /etc/localtime:/etc/localtime:ro
    env:
      PGID: 1000
      PUID: 1000
      TZ: "{{ timezone }}"
    ports:
      - "9117:9117"

- name: Plex Container
  become: true
  docker_container:
    name: plex
    network_mode: host
    restart_policy: unless-stopped
    image: linuxserver/plex
    volumes:
      - "{{ config_dir }}/plex/config:/config"
      - "{{ tv_dir }}:/data/tvshows"
      - "{{ movies_dir }}:/data/movies"
    env:
      PGID: 1000
      PUID: 1000
      TZ: "{{ timezone }}"
      VERSION: latest